### ISSUE TITLE
Could u please help me!?

### ISSUE THREAD

**Issue by notscream** [emregeldegul/confidant#7]
I never worked with Python or VirtualEnv, but i need ur project right now, could u help me and explain how to install ur proj, my virtualenv just doesn't working, which version exactly of python u used??

**Comment by GeorgeVasiliadis** [comment]
Hi there,

Have you tried following the installation steps provided [here](https://github.com/emregeldegul/confidant#installation)? If so, which step doesn't work for you? Could you provide the error message?

**Comment by emregeldegul** [comment]
Hi there.
This project use Python 3.8.9 but its not problem. I add version number of modules in requirements.txt file, its fix this problem.

if you want read about virtualenv  [click this link](https://www.freecodecamp.org/news/python-virtual-environments-explained-with-examples/#:~:text=virtualenv%20is%20a%20tool%20used,a%20Python%20project%20would%20need.)
